# openapi2-run.yaml
openapi: "3.0.1"
info:
  title: backed-api optional-string
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
#host: localhost:5000
#host: pi-j0dquon.ew.gateway.dev
#host: ds-j0dquon.ew.gateway.dev
#host: backed-api.apigateway.mussia8.cloud.goog
#host: aris-8jo9nv6l.ew.gateway.dev
#host: backed-api.apigateway.mussia8.cloud.goog
#schemes:
#  - http
#  - https
#produces:
#  - application/json

components:
  schemas:
    Provider:
      type: string
      default: local
      enum:
        - local
        - google
        - github

    Role:
      type: string
      enum: [editor, finance, admin, crm]
      default: admin

    User:
#      required:
#        - email
#        - firstName
      properties:
        _id:
          type: string
        isActive:
          type: boolean
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
        creditCardNumber:
          type: string
        provider:
          type: string
          $ref: '#/components/schemas/Provider'
        role:
          type: string
          $ref: '#/components/schemas/Role'
paths:
  /service1:
    get:
#      $ref: './packages/service1/dist/swagger.json'
      parameters:
        - in: query
          name: projection
          type: string
          required: false
          description: Array or string with spaces projection keys to fetch
          default: ''
        - in: query
          name: email
          type: string
          description: Search by email
        - in: query
          name: role
          type: string
          description: Search by role
          enum:
            $ref: '#/components/schemas/User'
          schema:
            type: enum
            $ref: '#/components/schemas/Role'
      tags:
        - Service1
      summary: Get service1 data
      operationId: getService1
      x-google-backend:
        address: https://service1-5g7d5fmura-lm.a.run.app/
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
#          schema:
#            items:
#              $ref: './packages/service1/dist/swagger.json#/definitions/User'
#          schema:
#            items:

    post:
      summary: Create service1 data
      operationId: postService1
      parameters:
        - in: body
          name: body
          description: Service1 object thats needs to be added to the db
          schema:
            $ref: '#/components/schemas/User'
      tags:
        - Service1
      x-google-backend:
        address: https://service1-5g7d5fmura-lm.a.run.app/
      responses:
        "200":
          description: A successful response
          schema:
            $ref: '#/components/schemas/User'
#            $ref: 'https://service1-5g7d5fmura-lm.a.run.app/swagger.json#/definitions/User'
  #
  #        put:
  #            parameters:
  #                - in: path
  #                  name: asset
  #                  type: string
  #                  required: true
  #                  description: Name of the asset.
  #            summary: Assets
  #            operationId: putService1
  #            x-google-backend:
  #                address: https://service1-5g7d5fmura-lm.a.run.app/
  #            responses:
  #                "200":
  #                    description: A successful response
  #                    schema:
  #                        type: string
  /service1/{id}:
    get:
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Id of the asset.
      tags:
        - Service1
      summary: Service1 get data
      operationId: getItem
      x-google-backend:
        address: https://service1-5g7d5fmura-lm.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: A successful response
          schema:
            $ref: '#/components/schemas/User'
#            $ref: 'https://service1-5g7d5fmura-lm.a.run.app/swagger.json#/definitions/User'
#        delete:
#            parameters:
#                - in: path
#                  name: asset
#                  type: string
#                  required: true
#                  description: Name of the asset.
#            summary: Assets
#            operationId: deleteService1
#            x-google-backend:
#                address: https://service1-5g7d5fmura-lm.a.run.app/
#            responses:
#                "200":
#                    description: A successful response
#    /service2:
#        get:
#            security:
#                - google_id_token
#            parameters:
#                - in: path
#                  name: asset
#                  type: string
#                  required: true
#                  description: Name of the asset.
#            summary: Assets
#            operationId: getService2
#            x-google-backend:
#                address: https://service2-5g7d5fmura-ew.a.run.app/
#            responses:
#                "200":
#                    description: A successful response
#                    schema:
#                        type: string

#securityDefinitions:
#  google_id_token:
#    flow: "implicit"
#    type: "oauth2"
#    x-google-issuer: "https://accounts.google.com"
#    authorizationUrl: "ars"
