# Deploys to gsc cloud run on change to service2
name: Service2
on:
    push:
        branches:
            - main
        paths:
            - "packages/service2/**"

jobs:
    gcp-deploy:
        runs-on:
            ubuntu-latest
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: "0"
            - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: mussia8
                  service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            - run: |-
                  gcloud --quiet auth configure-docker
            - name: GCP deploy
              run: npm run deploy -- -- scope=service2
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
                  NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
