name: Service1
on:
    push:
        branches:
            - main
        paths:
            - "packages/service1/**"
#            - "packages/ui/clients/**"
#            - "packages/ui/components/**"

jobs:
    billing-check:
        runs-on:
            ubuntu-latest

            #    strategy:
            #      matrix:
            #        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: "0"
            - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: mussia8
                  service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            - run: |-
                gcloud --quiet auth configure-docker
            - name: GCP deploy
              run: npm run deploy -- -- scope=service1
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
                  NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
