name: Tags and shit

on:
  - page_build
#  - deployment_status
#  - deployment
  - create
  - pull_request_review

jobs:
  labelPR:
    name: With tags
    runs-on: ubuntu-latest
    steps:
      - run: echo Release has happened
      - run: ls -a
